//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterExt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.customers = new HashSet<customer>();
            this.staffs = new HashSet<staff>();
            this.stores = new HashSet<store>();
        }
    
        public int address_id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string district { get; set; }
        public int city_id { get; set; }
        public string postal_code { get; set; }
        public string phone { get; set; }
        public System.DateTime last_update { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
        public virtual ICollection<store> stores { get; set; }
    }
}
