//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterExt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.addresses = new HashSet<address>();
        }
    
        public int city_id { get; set; }
        public string city1 { get; set; }
        public short country_id { get; set; }
        public System.DateTime last_update { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
        public virtual country country { get; set; }
    }
}
