//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterExt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public store()
        {
            this.customers = new HashSet<customer>();
            this.inventories = new HashSet<inventory>();
            this.staffs = new HashSet<staff>();
        }
    
        public int store_id { get; set; }
        public byte manager_staff_id { get; set; }
        public int address_id { get; set; }
        public System.DateTime last_update { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<inventory> inventories { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
        public virtual staff staff { get; set; }
    }
}
