//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterExt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public short id { get; set; }
        public string name { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string picture { get; set; }
    }
}
